const dimension = 2/100 * innerWidth;
let third_heading = document.getElementById("heading3");
let tools =document.getElementById("tools");
let list = document.getElementsByTagName("ul")[12];
let list2 = document.getElementsByTagName("ul")[13];
let title2 = document.getElementById("title2");
let second = document.getElementById("sec_2nd");
let content = document.getElementById("content");
let identification = document.getElementById("identification");
let header = document.getElementsByClassName("info")[0];
header.style = `width: ${99.9/100 * innerWidth}px;height: ${100/100 * innerHeight}px;`;
let title = document.getElementById("title");
title.style = `width: ${20/100 * 98/100*innerWidth}px; text-align: center;font-size: ${20/100 * 20/100 * 98/100 * innerWidth}px;color: white;`;
let styler = document.getElementById("styler");
styler.style = `width: ${76/100 * 98/100 * innerWidth}px;border-bottom: 3px dotted white;margin-left: ${1/100 * 98/100 * innerWidth}px;`;
identification.style = `width:${60/100 * 98/100 * innerWidth}px;height: ${60/100 * innerHeight}px;
margin-top: ${9/100*innerHeight}px;position: relative;color: white;font-size: ${2/100 * 98/100 * innerWidth}px;`;
identification.addEventListener("mouseover",()=>{identification.style = `width:${60/100 * 98/100 * innerWidth+dimension}px;height: ${60/100 * innerHeight}px;
margin-top: ${9/100*innerHeight}px;position: relative;color: white;font-size: ${2/100 * 98/100 * innerWidth}px`;});
identification.addEventListener("mouseout",()=>{identification.style = `width:${60/100 * 98/100 * innerWidth}px;height: ${60/100 * innerHeight}px;
margin-top: ${9/100*innerHeight}px;position: relative;color: white;font-size: ${2/100 * 98/100 * innerWidth}px`;});
second.style = `width: ${99.5/100 * innerWidth}px;height: ${7/100 * innerHeight}px;background-color: rgba(50,50,255,0.8);padding: ${1/200 * innerWidth}px;display: flex;align-items: center;`;
title2.style = `font-family: 'Montserrat', sans-serif;margin-left: ${2/100 * innerWidth}px;color: white;font-size: ${3/100 * innerWidth}px;`;
content.style = `height: ${1 * innerHeight}px;width: ${innerWidth}px;`;
list.style = `display: flex;height: 100%;flex-direction: column;justify-content: space-around;font-size: ${innerWidth * 2/100}px;margin-left: 20px;`;
tools.style = `position: absolute;top: ${innerHeight * 10/100}px;left: ${innerWidth * 40/100}px;width: ${60/100 * innerWidth}px;height: ${innerHeight}px;display: flex;flex-direction: column;padding: 5px;border-left: 2px solid white;`;
third_heading.style = `background-color: blue;`;
list2.style = `display: flex;height: 100%;width: ${60/100 * innerWidth}px;flex-direction: column;justify-content: space-between;margin: 8px;`;